#!/bin/bash
PREFIX='#'

significant_lines() {
	while read line; do
		if [ -z "$line" ]; then continue; fi
		if [ "$line" != "${line#$PREFIX}" ]; then continue; fi
		echo "$line"
	done
}

make_backup_point() {
	while read x; do
		echo "backup	$x	$1";
	done
}

find_user_config() {
	while read x; do
		find "$x";
	done | sort -u | comm --nocheck-order -23 - <(dlocate --filename-only -F '/etc' | grep '^/etc')
	# dlocate has a bug which prevents regexp from working properly
	# see #
	# otherwise we would use dlocate '^/etc' instead
}

subcmd="$1"
shift

case $subcmd in
make_backup_points )
	significant_lines | make_backup_point "./"
	;;
find_updated_configs )
	significant_lines | find_user_config
	debsums -ec
	;;
*)
	exit 1
	;;
esac
